version: "3.9"

services:
  mdmdb:
    container_name: mdmdb
    build: ./etc/docker/mariadb
    volumes:
      - ./etc/docker/mariadb/config:/etc/mysql/conf.d
    env_file:
      - ./etc/docker/mariadb/env/common.env
    restart: always
    ports:
      - "28004:3306"

